Send log to giganto
aicers/reproduce pull request #129
Opened 2022-09-21 04:15 UTC by BLYKIM

Add reconnecting logic when giganto server down

Close: #128

2022-09-21 23:52 UTC, BLYKIM commented on src/producer.rs
> +                    thread::sleep(std::time::Duration::from_secs(10));
아 생각해보니 계속 grow하는 파일을 읽고있는동안 giganto연결이 끊기면 확인하고 재접속하는 기능이 필요했네요 좀 더 생각해보겠습니다.

2022-09-23 22:54 UTC, msk requested changes

2022-09-23 22:54 UTC, msk commented on src/producer.rs
> +    async fn re_connect(&mut self) -> Result<()> {
`reconnect`는 한 단어니까 `_`는 빼는게 좋겠습니다.

2022-09-23 22:54 UTC, msk commented on src/producer.rs
> +                .expect("Failed to connect giganto, please check setting is correct")
이 에러는 reproduce 코드에는 문제가 없어도 사용자가 giganto의 주소를 잘못 입력했다거나 등의 이유로 충분히 일어날 수 있는 에러이므로 여기서 바로 panic하기보다는 에러를 리턴해서 caller쪽에서 처리할 수 있도록 하는 것이 바람직합니다.

2022-09-23 22:54 UTC, msk commented on src/producer.rs
> +                conn.open_bi().await.expect("Failed to open giganto stream");
이 에러도 giganto가 갑자기 실행을 멈추거나 네트워크에 문제가 생기거나 하면 생길 수 있는 에러이므로 에러를 리턴하는 것이 좋습니다.

2022-09-26 13:19 UTC, msk approved these changes

2022-09-26 13:19 UTC, merged