Release 0.12.1
aicers/reproduce pull request #204
Opened 2023-01-02 01:44 UTC by BLYKIM

- Deprecated Kafka server.

Release Issue: #196

2023-01-03 18:32 UTC, msk requested changes

2023-01-03 18:32 UTC, msk commented on CHANGELOG.md
> +### Removed
[Keep a Changelog](https://keepachangelog.com/en/1.0.0/)를 보시면 Deprecated 섹션이 따로 있습니다. Removed 대신 그걸 써 주세요.

2023-01-03 18:32 UTC, msk commented on CHANGELOG.md
> +## [0.12.1] - 2023-01-02
#203 에서 `-g` 용법이 바뀌었으니 0.13.0으로 올려주세요.

2023-01-03 19:19 UTC, msk commented
aicers/giganto#230 이후에 프로토콜 버전 업데이트해주세요.

2023-01-04 00:53 UTC, BLYKIM commented
선행 PR: aicers/giganto#231

2023-01-04 02:07 UTC, merged