[WIP]Remove Kafka
aicers/reproduce pull request #206
Opened 2023-01-04 03:15 UTC by BLYKIM

- Remove kafka, eventio

wip

2023-01-04 07:19 UTC, BLYKIM commented
@msk  @syncpark 
현재 Kafka 관련 코드들 중 Giganto에 영향이 없는 코드들을 지우면서 수정하고는 있는데,
Kafka에 전송하던 방식을 잘 몰라서 남겨야 하는 코드와  추가로 지워도 되는 코드 등에 대한 도움이 필요합니다.

2023-01-11 09:11 UTC, syncpark commented
@BLYKIM 

in config.rs:
* queue_size, queue_period, datasource_id, initial_seq_no 둘 모두 필요없습니다.

in controller.rs:
* run_single() function
  * report.start(), report.end()에서 id 값은 필요 없습니다. 이벤트의 시작 아이디와 끝 아이디를 적는 곳인데, 시간이 키가 되면서 더이상 일련번호가 아니거든요.
  * self.seq_no 값을 수정하는 코드도 필요 없습니다.
* get_seq_no() 함수도 필요 없습니다.

2023-01-12 00:58 UTC, syncpark requested changes

2023-01-12 00:58 UTC, syncpark commented on src/controller.rs
>      fn get_seq_no(&self, num: usize) -> usize {
이 함수 삭제하시고, 이 함수를 사용하는 부분에서도 관련 코드를 삭제해주세요.

2023-01-12 00:58 UTC, syncpark commented on src/controller.rs
> +                            giganto_msg.clear();
self.seq_no 이 값 필요없습니다.
report.start(), report.end() 함수 콜할 때 파라미터로 사용되는 값들도 필요없습니다.

2023-01-13 18:52 UTC, msk approved these changes

2023-01-16 04:28 UTC, syncpark approved these changes

2023-01-16 04:28 UTC, merged