Add new protocols and extend http field
aicers/reproduce pull request #316
Opened 2023-06-23 04:15 UTC by kimhanbeom

- Support for extended `struct Http` (orig_filenames/orig_mime_types/resp_filenames/resp_mime_types)
- Support for sending `gigaonto`/`zeek` logs for new protocols (`ldap`, `tls`).

2023-06-23 04:18 UTC, kimhanbeom commented
pending: https://github.com/aicers/giganto/issues/440

2023-06-23 08:22 UTC, syncpark approved these changes

2023-06-23 08:22 UTC, syncpark commented on CHANGELOG.md
> +- Support for sending `gigaonto`/`zeek` logs for new protocols (`ldap`, `tls`).
gigaonto -> giganto

2023-06-26 06:54 UTC, syncpark requested changes

2023-06-26 06:54 UTC, syncpark commented on src/zeek/network.rs
> +};
FTP 프로토콜이 안보임

2023-06-27 01:44 UTC, kimhanbeom commented
해당 사항들 수정 완료 했습니다.

2023-06-27 02:00 UTC, merged