Change to config read from file
aicers/reproduce pull request #465
Opened 2024-03-22 01:14 UTC by kimhanbeom

- Remove unnecessary or redundant command options.
- Modify some features that were only applicable to log types to be available to all types.
- Update README document.

Close: #455

2024-03-22 09:19 UTC, syncpark requested changes

2024-03-25 04:19 UTC, kimhanbeom commented on src/config.rs
> +            .context("cannot set the default file polling mode value")?
done

2024-03-26 01:48 UTC, syncpark approved these changes

2024-03-26 05:04 UTC, sophie-cluml reviewed
👍

2024-03-26 05:04 UTC, sophie-cluml commented on README.md
> +  report = false                           # Flag for transfer stats report.
Default is false.

가 있으면 더 도움이 될 것 같습니다. `file.polling_mode`, `file.export_from_giganto`, `common.kind`, `directory.polling_mode` 에도 마찬가지로 추가하면 더 좋을것 같아요. (코드에서 5개 항목에 대해서만 특별히 디폴트값을 세팅하고 있으므로)

2024-03-26 05:04 UTC, sophie-cluml commented on README.md
> +  kind ="http"                             # Data kind.
Default is empty string.

을 뒤에 추가하는 것은 어떤가요?

2024-03-26 06:17 UTC, kimhanbeom commented on src/producer.rs
> +        Ok(conv_cnt + skip)
다른 타입들과 달리 log의 경우에는 conv_cnt는 내가 전송한 line 갯수만을 의미하므로 skip을 더해야 실제 읽는 파일의 마지막 위치를 리턴 할 수 있습니다.

2024-03-26 06:23 UTC, kimhanbeom commented on README.md
> +  report = false                           # Flag for transfer stats report.
done

2024-03-26 06:23 UTC, kimhanbeom commented on README.md
> +  polling_mode = false                     # File polling mode flag.
done

2024-03-26 06:24 UTC, kimhanbeom commented on README.md
> +  kind ="http"                             # Data kind.
done

2024-03-26 08:04 UTC, merged